site_name: NTTãƒ‡ãƒ¼ã‚¿ãƒ»ãƒ‘ãƒ¼ã‚½ãƒ«ãƒ†ãƒ³ãƒ—ã‚¹ã‚¿ãƒƒãƒ•äº‹ä»¶ã€€ã‚»ã‚¯ãƒãƒ©ãƒ»å…¬ç›Šé€šå ±è€…å ±å¾©ãƒ»è¡Œæ”¿æŒ‡å°
site_description: NTTãƒ‡ãƒ¼ã‚¿ã§ã‚»ã‚¯ãƒãƒ©ã‚’å—ã‘ã¦å†…éƒ¨é€šå ±ã—ãŸã¨ã“ã‚é›‡æ­¢ã‚ã‚’å—ã‘ã¾ã—ãŸã€‚ã“ã®ã‚ˆã†ãªæ´¾é£åˆ¶åº¦ã®æ‚ªç”¨ã«å¯¾ã—ã¦å£°ã‚’ä¸Šã’ã¦ã„ã¾ã™ã€‚  # ã‚µã‚¤ãƒˆã®èª¬æ˜
site_url: https://minnanosaiban.github.io/ntt-data/
site_author: Mokeya
# copyright: Copyright &copy; 2025 â˜…â˜…â˜…

nav:
  - Home:
    - index.md
  - ãƒ–ãƒ­ã‚°:
    - blog/index.md    
  - äº‹ä»¶è§£èª¬:
    - sexual-harassment/index.md  
    - ğŸ”¹ç™ºç«¯ã¯ã‚»ã‚¯ãƒãƒ©: sexual-harassment/beginning.md
    - ğŸ”¹è¢«å®³ã‚’å…¬ç›Šé€šå ±: sexual-harassment/whistleblowing.md     
    - ğŸ”¹å›£ä½“äº¤æ¸‰æ‹’å¦: sexual-harassment/negotiation.md
    - ğŸ”¹è¢«å®³è€…ã‚’é›‡æ­¢ã‚: sexual-harassment/fire.md
    - ğŸ”¹è¡Œæ”¿æŒ‡å°ã‚’ã‚¹ãƒ«ãƒ¼: sexual-harassment/administrative-guidance.md
    - ğŸ”¹æ±åŠ´å§”å¯©æŸ»ç”³ç«‹ã¦: sexual-harassment/petition.md
    - ğŸ”¹å¯©ç†ã®äº‰ç‚¹: sexual-harassment/issue.md
    - ğŸ”¹æ±åŠ´å§”å‘½ä»¤æ›¸å…¬å¸ƒ: sexual-harassment/toroui-order.md
  - ChatGPTã§è§£èª¬:
    - chatgpt/index.md
    - ğŸ”¹å‘½ä»¤æ›¸ã‚’ã‚®ãƒ£ãƒ«èªã§è§£èª¬: chatgpt/toroui-order.md
  - è£åˆ¤æ–‡æ›¸åŸæ–‡ <i class="bi bi-arrow-up-right"></i>:
    - https://minnanosaiban.github.io/ntt-data-doc/

extra_css:
  - css/custom.css
  - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

extra_javascript:
  - js/custom.js

theme:
  name: "material"
  custom_dir: overrides # ã‚«ã‚¹ã‚¿ãƒã‚¤ã‚ºç”¨ã®ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒª
  language: ja # ã‚µã‚¤ãƒˆã®è¨€èªè¨­å®š
  logo: assets/images/logo.png # ã‚µã‚¤ãƒˆå·¦ä¸Šã®ã‚¢ã‚¤ã‚³ãƒ³
  favicon: assets/images/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: ãƒ€ãƒ¼ã‚¯ãƒ¢ãƒ¼ãƒ‰ã«åˆ‡ã‚Šæ›¿ãˆã¾ã™
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: ãƒ©ã‚¤ãƒˆãƒ¢ãƒ¼ãƒ‰ã«åˆ‡ã‚Šæ›¿ãˆã¾ã™

  features:
    - content.code.annotate # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯å†…ã®æ³¨é‡ˆ
    - content.code.copy # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ã€Œã‚³ãƒ”ãƒ¼ã€ãƒœã‚¿ãƒ³
    - content.code.select # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ç¯„å›²é¸æŠæ©Ÿèƒ½
    - content.footnote.tooltips # è„šæ³¨ã‚’ãƒ„ãƒ¼ãƒ«ãƒãƒƒãƒ—ã¨ã—ã¦è¡¨ç¤º
    - content.tabs.link # ã‚¿ãƒ–é–“ã®ãƒªãƒ³ã‚¯ã‚’æœ‰åŠ¹åŒ–
    - content.tooltips # ãƒ„ãƒ¼ãƒ«ãƒãƒƒãƒ—ï¼ˆè£œè¶³èª¬æ˜ã®ãƒãƒƒãƒ—ã‚¢ãƒƒãƒ—ï¼‰ã‚’æœ‰åŠ¹åŒ–
    - header.autohide # ãƒ˜ãƒƒãƒ€ãƒ¼ãŒéš ã‚Œã‚‹
    - navigation.tracking # ãƒšãƒ¼ã‚¸ã®ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã«å¿œã˜ã¦ã€è¦‹å‡ºã—ã‚’æ›´æ–°
    - navigation.tabs # ã‚¿ãƒ–å½¢å¼ã®ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³
    - navigation.expand # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚’æœ€åˆã‹ã‚‰ã™ã¹ã¦å±•é–‹
    - navigation.top # ãƒˆãƒƒãƒ—ã¸æˆ»ã‚‹ãƒœã‚¿ãƒ³
    - navigation.indexes # index.md ã‚’å«ã‚€ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®è¦ªã¨ã—ã¦æ‰±ã†
    - navigation.expand # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚’æœ€åˆã‹ã‚‰ã™ã¹ã¦å±•é–‹
    - navigation.sections # æŠ˜ã‚ŠãŸãŸã¾ãšã«å…¨ã¦ãƒ•ãƒ©ãƒƒãƒˆã«è¡¨ç¤º
    - navigation.path # ï¼Ÿ
    - toc.follow # TOCãŒã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã«å¿œã˜ã¦ç¾åœ¨ã®è¦‹å‡ºã—ã‚’è¿½å¾“

    # - announce.dismiss # ã‚¢ãƒŠã‚¦ãƒ³ã‚¹ãƒãƒ¼ã‚’è¡¨ç¤º
    # - content.action.edit # ã€Œç·¨é›†ã€ãƒœã‚¿ãƒ³ã‚’è¡¨ç¤º
    # - content.action.view # ã€Œã‚½ãƒ¼ã‚¹ã‚’è¡¨ç¤ºã€ãƒœã‚¿ãƒ³
    # - content.code.annotate # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯å†…ã®æ³¨é‡ˆ
    # - content.code.copy # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ã€Œã‚³ãƒ”ãƒ¼ã€ãƒœã‚¿ãƒ³
    # - content.code.select # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ç¯„å›²é¸æŠæ©Ÿèƒ½
    # - content.footnote.tooltips # è„šæ³¨ã‚’ãƒ„ãƒ¼ãƒ«ãƒãƒƒãƒ—ã¨ã—ã¦è¡¨ç¤º
    # - content.tabs.links # ã‚¿ãƒ–é–“ã®ãƒªãƒ³ã‚¯ã‚’æœ‰åŠ¹åŒ–
    # - content.tooltips # ãƒ„ãƒ¼ãƒ«ãƒãƒƒãƒ—ï¼ˆè£œè¶³èª¬æ˜ã®ãƒãƒƒãƒ—ã‚¢ãƒƒãƒ—ï¼‰ã‚’æœ‰åŠ¹åŒ–
    # - header.autohide # ãƒ˜ãƒƒãƒ€ãƒ¼ãŒéš ã‚Œã‚‹
    # - navigation.expand # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚’æœ€åˆã‹ã‚‰ã™ã¹ã¦å±•é–‹
    # - navigation.sections # æŠ˜ã‚ŠãŸãŸã¾ãšã«å…¨ã¦ãƒ•ãƒ©ãƒƒãƒˆã«è¡¨ç¤º
    # - navigation.footer # ãƒšãƒ¼ã‚¸ä¸‹éƒ¨ã«ã€Œå‰ã¸ãƒ»æ¬¡ã¸ã€ã®ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³
    # - navigation.indexes # index.md ã‚’å«ã‚€ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®è¦ªã¨ã—ã¦æ‰±ã†
    # - navigation.instant # ãƒšãƒ¼ã‚¸é·ç§»ã‚’é«˜é€ŸåŒ–ã™ã‚‹ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ãƒˆãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³
    # - navigation.instant.prefetch # ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ãƒˆãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®ãƒ—ãƒªãƒ•ã‚§ãƒƒãƒï¼ˆäº‹å‰èª­ã¿è¾¼ã¿ï¼‰
    # - navigation.instant.progress # ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ãƒˆãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®èª­ã¿è¾¼ã¿é€²è¡ŒçŠ¶æ³ã‚’è¡¨ç¤º
    # - navigation.prune # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®ãƒ¡ãƒ‹ãƒ¥ãƒ¼é …ç›®ã‚’ç¸®å°ã—ã€å¿…è¦ãªã‚‚ã®ã ã‘è¡¨ç¤º
    # - navigation.tabs # ã‚¿ãƒ–å½¢å¼ã®ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³
    # - navigation.tabs.sticky # ã‚¿ãƒ–å½¢å¼ã®ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã‚’ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã—ã¦ã‚‚ä¸Šéƒ¨ã«å›ºå®š
    # - navigation.top # ãƒˆãƒƒãƒ—ã¸æˆ»ã‚‹ãƒœã‚¿ãƒ³
    # - navigation.tracking  # ãƒšãƒ¼ã‚¸ã®ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã«å¿œã˜ã¦ã€è¦‹å‡ºã—ã‚’æ›´æ–°
    # - toc.follow # TOCãŒã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ã«å¿œã˜ã¦ç¾åœ¨ã®è¦‹å‡ºã—ã‚’è¿½å¾“
    # - toc.integrate # TOCã‚’ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã®ä¸€éƒ¨ã¨ã—ã¦çµ±åˆ
    # - search.highlight # æ¤œç´¢çµæœã®ãƒã‚¤ãƒ©ã‚¤ãƒˆè¡¨ç¤º
    # - search.share # æ¤œç´¢çµæœã® URL ã‚’ã‚³ãƒ”ãƒ¼ã™ã‚‹ãƒœã‚¿ãƒ³
    # - search.suggest # æ¤œç´¢æ™‚ã«ã€é–¢é€£ã™ã‚‹æ¤œç´¢å€™è£œã‚’è¡¨ç¤º

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      # js_files:
        # - js/toc.js
      # - css_files:
        # - css/custom.css
        # - css/card.css
  - blog
  # - tags:
    # tags_file: tags.md
  # - blogging:
      # locale: ja
      # dirs:
        # - Blogs/posts
      # theme:
        # name: card
      # features:
        # tags:
          # index_page: tags/
          # insert: top
  # - search # è¿½åŠ ã®éš›ã¯ã€Œfeaturesã€ã‚‚è¨­å®šã™ã‚‹
  # - callouts # admonitionã¨åŒæ§˜ã®æ©Ÿèƒ½
  # - glightbox: # ç”»åƒãƒ»å‹•ç”»ã®ãƒãƒƒãƒ—ã‚¢ãƒƒãƒ—è¡¨ç¤º
    # width: 80%
  # - heti
  # - include_dir_to_nav:
  #     sort_file: true
  #     sort_directory: true

# extra:
  # not_in_nav:  # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã‹ã‚‰é™¤å¤–
    # - hidden_page.md
    # - secret_folder/*
  # status:  # ãƒ•ãƒ­ãƒ³ãƒˆãƒã‚¿ãƒ¼ã«è¨˜è¼‰ã™ã‚‹ã¨ã€ŒNew!ã€ã¨è¡¨ç¤º
    # new: "New!"

# hooks: # ãƒã‚¯ãƒ­ã®ã‚ˆã†ã«å®šå‹å‡¦ç†ã‚’è‡ªå‹•åŒ–
  # - overrides/hooks/shortcodes.py
  # - overrides/hooks/translations.py

validation: # ãƒŠãƒ“ã‚²ãƒ¼ã‚·ãƒ§ãƒ³ã‚„ãƒªãƒ³ã‚¯ãŒåˆ‡ã‚Œã‚‹ã“ã¨ãŒæ°—ã«ãªã‚‹ã¨ãã«è¨­å®š
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn

markdown_extensions:
  - meta # ãƒ•ãƒ­ãƒ³ãƒˆãƒã‚¿ãƒ¼ã‚’ä½¿ãˆã‚‹ã‚ˆã†ã«ã™ã‚‹
  - md_in_html # ãƒãƒ¼ã‚¯ãƒ€ã‚¦ãƒ³ã¨htmlã‚’ä¸€ç·’ã«ä½¿ã†
  - attr_list # ãƒãƒ¼ã‚¯ãƒ€ã‚¦ãƒ³ã§ã‚‚htmlå±æ€§ã‚’è¨­å®šã™ã‚‹ã“ã¨ãŒã§ãã‚‹
  - nl2br # ã‚¹ãƒšãƒ¼ã‚¹2ã¤ä»˜ã‘ãªãã¦ã‚‚æ”¹è¡Œ
  - sane_lists # ãƒªã‚¹ãƒˆã®èª¤å‹•ä½œã‚’é˜²ã
  - toc: # tocã‚’è‡ªå‹•çš„ã«ç”Ÿæˆ
      toc_depth: 3 # tocã®æ·±ã•
  - pymdownx.emoji: # çµµæ–‡å­—ã‚’ä½¿ã†
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.smartsymbols # ãƒ€ãƒ–ãƒ«ã‚¯ã‚©ãƒ¼ãƒ†ãƒ¼ã‚·ãƒ§ãƒ³ç­‰ã®è¡¨ç¤ºã‚’ã‚­ãƒ¬ã‚¤ã«ã™ã‚‹
  - pymdownx.caret # ã‚­ãƒ£ãƒ¬ãƒƒãƒˆè¨˜å·ï¼ˆ^ï¼‰ã«ã‚ˆã‚‹supã‚¿ã‚°ï¼ˆä¸Šä»˜ãæ–‡å­—ï¼‰
  - pymdownx.details # detailsã‚¿ã‚°ã«ã‚ˆã‚‹æŠ˜ã‚Šç•³ã¿å‡¦ç†
  - pymdownx.mark # markã‚¿ã‚°ï¼ˆãƒã‚¤ãƒ©ã‚¤ãƒˆï¼‰
  - pymdownx.betterem: # emã‚¿ã‚°ã‚„strongã‚¿ã‚°ï¼ˆå¼·èª¿ï¼‰ã‚’åŒºåˆ¥ã™ã‚‹

  # - meta # ãƒ•ãƒ­ãƒ³ãƒˆãƒã‚¿ãƒ¼ã‚’ä½¿ãˆã‚‹ã‚ˆã†ã«ã™ã‚‹
  # - md_in_html # ãƒãƒ¼ã‚¯ãƒ€ã‚¦ãƒ³ã¨htmlã‚’ä¸€ç·’ã«ä½¿ã†
  # - attr_list # ãƒãƒ¼ã‚¯ãƒ€ã‚¦ãƒ³ã§ã‚‚htmlå±æ€§ã‚’è¨­å®šã™ã‚‹ã“ã¨ãŒã§ãã‚‹
  # - nl2br # ã‚¹ãƒšãƒ¼ã‚¹2ã¤ä»˜ã‘ãªãã¦ã‚‚æ”¹è¡Œ
  # - sane_lists # ãƒªã‚¹ãƒˆã®èª¤å‹•ä½œã‚’é˜²ã
  # - abbr # ç•¥èªã®å®šç¾©
  # - admonition # admonitionã‚«ãƒ¼ãƒ‰
  # - def_list # å®šç¾©èªã®ãƒªã‚¹ãƒˆ
  # - footnotes # æ–‡æœ«è„šæ³¨
  # - toc: # tocã‚’è‡ªå‹•çš„ã«ç”Ÿæˆ
    # permalink: true # h1ã‚„h2ã«ãƒ‘ãƒ¼ãƒãƒªãƒ³ã‚¯ã‚’è¡¨ç¤º
    # toc_depth: 3 # tocã®æ·±ã•
  # - codehilite: # ã‚³ãƒ¼ãƒ‰ãƒã‚¤ãƒ©ã‚¤ãƒˆ
      # guess_lang: false
  # - pymdownx.emoji: # çµµæ–‡å­—ã‚’ä½¿ã†
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
  # - pymdownx.smartsymbols # ãƒ€ãƒ–ãƒ«ã‚¯ã‚©ãƒ¼ãƒ†ãƒ¼ã‚·ãƒ§ãƒ³ç­‰ã®è¡¨ç¤ºã‚’ã‚­ãƒ¬ã‚¤ã«ã™ã‚‹
  # - pymdownx.caret # ã‚­ãƒ£ãƒ¬ãƒƒãƒˆè¨˜å·ï¼ˆ^ï¼‰ã«ã‚ˆã‚‹supã‚¿ã‚°ï¼ˆä¸Šä»˜ãæ–‡å­—ï¼‰
  # - pymdownx.details # detailsã‚¿ã‚°ã«ã‚ˆã‚‹æŠ˜ã‚Šç•³ã¿å‡¦ç†
  # - pymdownx.mark # markã‚¿ã‚°ï¼ˆãƒã‚¤ãƒ©ã‚¤ãƒˆï¼‰
  # - pymdownx.betterem: # emã‚¿ã‚°ã‚„strongã‚¿ã‚°ï¼ˆå¼·èª¿ï¼‰ã‚’åŒºåˆ¥ã™ã‚‹
  # - pymdownx.tabbed: # ã‚¿ãƒ–ã®è¨­å®š
      # alternate_style: true
      # combine_header_slug: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
        # kwds:
          # case: lower
  # - pymdownx.tasklist: # ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆã®è¨­å®š
      # custom_checkbox: true
  # - pymdownx.tilde # ãƒãƒ«ãƒ‰è¨˜å·ï¼ˆ~ï¼‰ã«ã‚ˆã‚‹å–ã‚Šæ¶ˆã—ç·š 
  # - pymdownx.critic # æ ¡æ­£ç­‰ã®ã‚³ãƒ¡ãƒ³ãƒˆ 
  # - pymdownx.magiclink: # ãƒªãƒ³ã‚¯ã®è¨˜è¿°ã‚’ç°¡æ˜“ã«ã™ã‚‹
      # normalize_issue_symbols: true
      # repo_url_shorthand: true
      # user: squidfunk
      # repo: mkdocs-material
    # - pymdownx.snippets:  # å…¨ã¦ã®ãƒšãƒ¼ã‚¸ã®æœ«å°¾ã«è¿½åŠ ã™ã‚‹
      # auto_append:
        # - includes/mkdocs.md
  # - pymdownx.arithmatex: # æ•°å¼
    # generic: true # æ•°å¼ã‚’æ±ç”¨çš„ã«å‡¦ç†
  # - pymdownx.highlight: # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ãƒã‚¤ãƒ©ã‚¤ãƒˆ
      # anchor_linenums: true
      # line_spans: __span
      # pygments_lang_class: true
  # - pymdownx.inlinehilite # ã‚¤ãƒ³ãƒ©ã‚¤ãƒ³ã‚³ãƒ¼ãƒ‰ãƒã‚¤ãƒ©ã‚¤ãƒˆ
  # - pymdownx.superfences: # è¤‡é›‘ãªã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®å‡¦ç†ã€‚
      # custom_fences:
        # - name: mermaid
          # class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format